AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Api:
    Cors:
      AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
      AllowHeaders: "'Content-Type,Authorization'"
      AllowOrigin: "'*'"
  Function:
    Timeout: 10
    Runtime: nodejs20.x
    Environment:
      Variables:
        USERS_TABLE: users
        SCHOOLS_TABLE: schools
        CLASSES_TABLE: classes
        STUDENTS_TABLE: students

Resources:

  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: auth/index.lambdaHandler
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: sam-app-test/jwt-secret
        - DynamoDBCrudPolicy:
            TableName: users
      Events:
        Register:
          Type: Api
          Properties:
            Path: /auth/{proxy+}
            Method: ANY
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints: [auth/index.ts]

  SchoolsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: schools/index.lambdaHandler
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: sam-app-test/jwt-secret
        - DynamoDBCrudPolicy:
            TableName: schools
        - DynamoDBCrudPolicy:
            TableName: classes
      Events:
        Schools:
          Type: Api
          Properties:
            Path: /schools/{proxy+}
            Method: ANY
        SchoolsRoot:
          Type: Api
          Properties:
            Path: /schools
            Method: ANY
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints: [schools/index.ts]

  ClassesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: classes/index.lambdaHandler
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: sam-app-test/jwt-secret
        - DynamoDBCrudPolicy:
            TableName: classes
        - DynamoDBCrudPolicy:
            TableName: schools
      Events:
        SchoolClasses:
          Type: Api
          Properties:
            Path: /schools/{schoolId}/classes
            Method: ANY
        SchoolClassesProxy:
          Type: Api
          Properties:
            Path: /schools/{schoolId}/classes/{proxy+}
            Method: ANY
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints: [classes/index.ts]

  StudentsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: students/index.lambdaHandler
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: sam-app-test/jwt-secret
        - DynamoDBCrudPolicy:
            TableName: students
        - DynamoDBCrudPolicy:
            TableName: classes
        - DynamoDBCrudPolicy:
            TableName: schools
      Events:
        StudentsRoot:
          Type: Api
          Properties:
            Path: /students
            Method: ANY
        StudentsProxy:
          Type: Api
          Properties:
            Path: /students/{studentId}
            Method: ANY
        ClassStudents:
          Type: Api
          Properties:
            Path: /classes/{classId}/students
            Method: ANY
        ClassStudentsProxy:
          Type: Api
          Properties:
            Path: /classes/{classId}/students/{proxy+}
            Method: ANY
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints: [students/index.ts]

Outputs:
  ApiUrl:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"